version: "3.7"
services:
  sadFavBot:
    build: .
    image: kozalosev/sadfavbot
    container_name: sadfavbot
    restart: unless-stopped
    environment:
      - API_TOKEN
      - DEBUG
      - COMMAND_STATE_TTL
      - APP_PORT
      - APP_PATH
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - MIGRATIONS_REPO
      - WEBHOOK_HOST
      - WEBHOOK_PORT
      - WEBHOOK_PATH
    expose:
      - ${APP_PORT}
    depends_on:
      - postgres
      - redis
    networks:
      - postgres-network
      - redis-network
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    logging:
      driver: local
  postgres:
    image: postgres:14.5-alpine
    container_name: sadfavbot-postgresql
    environment:
      - POSTGRES_PORT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - PGDATA=/var/lib/postgresql/data/pgdata
    expose:
      - ${POSTGRES_PORT}
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - postgres-network
    logging:
      driver: local
  redis:
    image: redis:6.2-alpine
    container_name: sadfavbot-redis
    restart: unless-stopped
    expose:
      - ${REDIS_PORT}
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD:?error} --port ${REDIS_PORT}
    volumes:
      - ./data/redis:/data
    networks:
      - redis-network
    logging:
      driver: local
networks:
  postgres-network:
    driver: bridge
  redis-network:
    driver: bridge
