package main

func init() {
	locpool.Resources["en"] = map[string]string{
		"error":                               "Error",
		"success":                             "👍👌",
		"commands.default.message":            "No command was selected. Send /help to know about my skills",
		"commands.default.message.on.command": "Unknown command. Send /help to know about my skills",
		"commands.start.status.failure":       "Something went wrong... Please, try again later or contact @kozalo",
		"commands.save.fields.alias":          "Enter a name for your fav",
		"commands.save.fields.object":         "Send an object to me",
		"commands.save.fields.alias.validation.error.length":  "The maximum length of the name must be less than %d characters",
		"commands.save.fields.object.validation.error.length": "The maximum length of the text must be less than %d characters",
		"commands.save.status.success":                        "Saved successfully",
		"commands.save.status.failure":                        "An error occurred while saving; please, try again later or contact @kozalo",
		"commands.save.status.duplicate":                      "This item is already present in the collection",
		"commands.list.status.success":                        "Saved aliases (with the count of associated objects):",
		"commands.list.status.failure":                        "An error occurred while executing the query; please, try again later or contact @kozalo",
		"commands.list.status.no.rows":                        "You have no saved aliases. It's time to make use of the /save command!",
		"commands.delete.fields.alias":                        "Enter an alias",
		"commands.delete.fields.deleteAll":                    "Do you want to delete all objects associated with this alias?",
		"commands.delete.fields.object":                       "Send me an an object",
		"commands.delete.button.select.object":				   "Select…",
		"commands.delete.status.success":                      "Deleted successfully",
		"commands.delete.status.failure":                      "An error occurred while deletion; please, try again later or contact @kozalo",
		"commands.delete.status.no.rows":                      "Such object wasn't found",
		"commands.language.fields.language":                   "Choose your language:",
		"commands.language.status.failure":                    "An error has been occurred while saving your settings; please, try again later or contact @kozalo",
		"wizard.active.not.set":                               "There is nothing to cancel ☹",
		"wizard.errors.field.invalid.value":                   "Validation error: ",
		"wizard.errors.field.invalid.type":                    "The following type was expected: ",
		"wizard.errors.state.missing":                         "The state of your operation is missing; probably, the bot was restarted; please, try again from the beginning",
		"inline.errors.type.invalid":                          "Unknown type; contact me if you want it to be supported: @kozalo",
		"errors.validation.option.not.in.list":                "Option is not from suggested variants",
		"callbacks.error":                                     "An unknown error has been occurred, try again later or contact @kozalo",

		"video_note": "video note",
	}

	locpool.Resources["ru"] = map[string]string{
		"error":                               "Ошибка",
		"success":                             "👍👌",
		"commands.default.message":            "Ни одна команда не была выбрана. Отправьте /help, чтобы узнать о моих возможностях",
		"commands.default.message.on.command": "Неизвестная команда. Отправьте /help, чтобы узнать о моих возможностях",
		"commands.start.status.failure":       "Что-то пошло не так... Пожалуйста, повторите позднее или напишите @kozalo",
		"commands.save.fields.alias":          "Введите имя для закладки",
		"commands.save.fields.object":         "Отправьте объект",
		"commands.save.fields.alias.validation.error.length":  "Имя не может быть длиннее %d символов",
		"commands.save.fields.object.validation.error.length": "Текст не может быть длиннее %d символов",
		"commands.save.status.success":                        "Успешно сохранено",
		"commands.save.status.failure":                        "При сохранении произошла ошибка, попробуйте позже или напишите @kozalo",
		"commands.save.status.duplicate":                      "Данный объект уже присутствует в коллекции",
		"commands.list.status.success":                        "Сохранённые закладки (с количеством ассоциированных объектов):",
		"commands.list.status.failure":                        "При выполнении запроса произошла ошибка, попробуйте позже или напишите @kozalo",
		"commands.list.status.no.rows":                        "У вас нет никаких закладок. Самое время воспользоваться командой /save!",
		"commands.delete.fields.alias":                        "Введите имя",
		"commands.delete.fields.deleteAll":                    "Вы хотите удалить все объекты под этим именем?",
		"commands.delete.fields.object":                       "Отправьте удаляемый объект",
		"commands.delete.button.select.object":				   "Выбрать…",
		"commands.delete.status.success":                      "Успешно удалено",
		"commands.delete.status.failure":                      "При удалении произошла ошибка, пожалуйста, попробуйте позже или напишите @kozalo",
		"commands.delete.status.no.rows":                      "Такой объект не был найден",
		"commands.language.fields.language":                   "Выберите свой язык:",
		"commands.language.status.failure":                    "При сохранении выбранного языка произошла ошибка. Попробуйте позже или напишите @kozalo",
		"wizard.active.not.set":                               "Нечего отменять ☹",
		"wizard.errors.field.invalid.value":                   "Ошибка валидации: ",
		"wizard.errors.field.invalid.type":                    "Ожидался следующий тип: ",
		"wizard.errors.state.missing":                         "Состояние операции потеряно; возможно, бот был перезапущен; пожалуйста, попробуйте повторить операцию с самого начала",
		"inline.errors.type.invalid":                          "Неизвестный тип; свяжитесь со мной, если хотите, чтобы он поддерживался: @kozalo",
		"errors.validation.option.not.in.list":                "Введённого варианта нет в предложенном списке",
		"callbacks.error":                                     "Произошла неизвестная ошибка, попробуйте позже или напишите @kozalo",

		"text":       "текст",
		"image":      "изображение",
		"gif":        "гифка",
		"video":      "видеозапись",
		"video_note": "видеосообщение",
		"sticker":    "стикер",
		"voice":      "аудиосообщение",
		"audio":      "аудиозапись",
	}
}
